### ISSUE TITLE
BlackMarket should count as negative trade

### ISSUE THREAD

**Issue by cluster-fox** [tezw21/BGS-Tally-Comguard#2]
When a commander performs a BlackMarket type:
Example journal:
_{
    "event": "MarketSell",
    "Type": "mineraloil",
    "Count": 9,
    "SellPrice": 72,
    "TotalSale": 648,
    "AvgPricePaid": 0,
    "StolenGoods": true,
    "BlackMarket": true
}_

1. 
Function send_data()
Set payload->data->type to "BlackMarket"
Send value as positive

2.
Consider the value as a negative when adding to the client's Tally arrays

**Comment by tezw21** [comment]
it appears this has also been done, please confirm and I'll close the issue
