### ISSUE TITLE
Feature request: Send Factions arrays

### ISSUE THREAD

**Issue by cluster-fox** [tezw21/BGS-Tally-Comguard#3]
There's reasons to run silent (EDDN / Inara OFF) when doing BGS.
Comguard can keep track of Faction INF and State independently from EDDN / EDSM / EBGS.

On events: 
- FSDJump
- Location
- CarrierJump

The _Factions_ array is valuable information for Comguard

Perfect format would be:

    payload = {
        "key": this.APIKey.get(),
        "data": {
            "timestamp" : timestamp,
            "event" : event,
            "type" : NULL,
            "system" : StarSystem,
            "faction" : Factions[],
            "value" : SystemAddress
        }
    }

**Comment by tezw21** [comment]
It appears this has been done, please confirm and I'll close the issue
