### ISSUE TITLE
Feature Request: Test API button or API error message handling

### ISSUE THREAD

**Issue by cluster-fox** [tezw21/BGS-Tally-Comguard#4]
There is little feedback to let the user know if the API key is entered correctly or not.

Option 1. To confirm the user entered the API key correctly, a test API button in the settings would be useful.
- Format to be discussed.
- Could easily use the event endpoint. 
- Could simply read the HTTP Status code (200 is good, 401 means bad api Key).

Option 2. Display when an error code is returned by the API during routine calls.
Error format is:
```
{ "error": { 
  "errors": [
      {
        "domain": String,
        "reason": String,
        "message": String,
        "locationType": String,
        "location": String
      }, ...  ],
    "code": 400 | 401,
    "message": String
  }
}
```
error['code'] and error['message'] give the general information about the error.

**Comment by tezw21** [comment]
Response is currently written to the log. There used to be a way to display an error at the bottom of main window, I could look into that option

**Comment by cluster-fox** [comment]
This has been added. Issue closed
